CXXFLAGS="-std=c++17" LDFLAGS="$($TERMUX_SCRIPTDIR/packages/libprotobuf/interface_link_libraries.sh) -llog" 

TERMUX_PKG_EXTRA_CONFIGURE_ARGS="-DANDROID_NO_TERMUX=OFF
-DWITH_GSTREAMER=OFF
-DWITH_OPENEXR=OFF
-DWITH_QT=6
-DBUILD_PERF_TESTS=OFF
-DBUILD_PROTOBUF=OFF
-DBUILD_TESTS=OFF
-DPROTOBUF_UPDATE_FILES=ON
-DOPENCV_GENERATE_PKGCONFIG=ON
-DOPENCV_SKIP_CMAKE_CXX_STANDARD=ON
"


TERMUX_PKG_EXTRA_CONFIGURE_ARGS="$TERMUX_PKG_EXTRA_CONFIGURE_ARGS
-DPYTHON_DEFAULT_EXECUTABLE=python
-DPYTHON3_INCLUDE_PATH=$TERMUX_PREFIX/include/python${TERMUX_PYTHON_VERSION:-3.12}
-DPYTHON3_NUMPY_INCLUDE_DIRS=${TERMUX_PYTHON_HOME:=$TERMUX_PREFIX/lib/python${TERMUX_PYTHON_VERSION:-3.12}}/site-packages/numpy/_core/include
"
