export default {
  refs: ['class', 'device', 'deviceset', 'element', 'gate', 'layer', 'library', 'module', 'moduleinst', 'package', 'pad', 'part', 'pin', 'port', 'symbol', 'technology'],
  element: {
    approved: ['hash'],
    attribute: ['name', 'x', 'y', 'size', 'layer', 'rot', 'align', 'ratio', 'value', 'constant', 'font', 'display'],
    bus: ['name'],
    circle: ['x', 'y', 'radius', 'width', 'layer'],
    class: ['number', 'name', 'width', 'drill'],
    clearance: ['class', 'value'],
    connect: ['gate', 'pin', 'pad', 'route'],
    contactref: ['element', 'pad'],
    description: ['language'],
    designrules: ['name'],
    device: ['name', 'package'],
    deviceset: ['name', 'prefix', 'uservalue'],
    dimension: ['x1', 'y1', 'x2', 'y2', 'x3', 'y3', 'textsize', 'textratio', 'layer', 'dtype', 'visible', 'unit', 'precision', 'width', 'extwidth'],
    eagle: ['version'],
    element: ['name', 'library', 'package', 'value', 'x', 'y', 'rot', 'smashed'],
    frame: ['x1', 'y1', 'x2', 'y2', 'columns', 'rows', 'layer'],
    gate: ['name', 'symbol', 'x', 'y', 'swaplevel', 'addlevel'],
    grid: ['distance', 'unitdist', 'unit', 'style', 'multiple', 'display', 'altdistance', 'altunitdist', 'altunit'],
    hole: ['x', 'y', 'drill'],
    instance: ['part', 'gate', 'x', 'y', 'rot', 'smashed'],
    junction: ['x', 'y'],
    label: ['x', 'y', 'size', 'layer', 'rot', 'xref', 'ratio'],
    layer: ['number', 'name', 'color', 'fill', 'visible', 'active'],
    library: ['name'],
    module: ['name', 'prefix', 'dx', 'dy'],
    moduleinst: ['name', 'module', 'x', 'y'],
    net: ['name', 'class'],
    note: ['version', 'minversion', 'severity'],
    package: ['name'],
    pad: ['name', 'x', 'y', 'drill', 'diameter', 'rot', 'shape', 'stop', 'first', 'thermals'],
    param: ['name', 'value'],
    part: ['name', 'library', 'deviceset', 'device', 'value', 'technology'],
    pass: ['name', 'refer', 'active'],
    pin: ['name', 'x', 'y', 'visible', 'length', 'direction', 'swaplevel', 'rot', 'function'],
    pinref: ['part', 'gate', 'pin'],
    polygon: ['width', 'layer', 'isolate', 'thermals'],
    port: ['name', 'side', 'coord', 'direction'],
    portref: ['moduleinst', 'port'],
    rectangle: ['x1', 'y1', 'x2', 'y2', 'layer', 'rot'],
    schematic: ['xreflabel', 'xrefpart'],
    setting: ['alwaysvectorfont', 'verticaltext'],
    signal: ['name'],
    smd: ['name', 'x', 'y', 'dx', 'dy', 'layer', 'rot', 'stop', 'cream', 'roundness', 'thermals'],
    symbol: ['name'],
    technology: ['name'],
    text: ['x', 'y', 'size', 'layer', 'ratio', 'rot', 'align', 'font', 'distance'],
    version: ['encoding'],
    vertex: ['x', 'y', 'curve'],
    via: ['x', 'y', 'extent', 'drill', 'shape', 'diameter'],
    wire: ['x1', 'y1', 'x2', 'y2', 'width', 'layer', 'curve', 'style', 'cap', 'extent'],
  },
  prop: {
    active: ['layer', 'pass'],
    addlevel: ['gate'],
    align: ['text', 'attribute'],
    altdistance: ['grid'],
    altunit: ['grid'],
    altunitdist: ['grid'],
    alwaysvectorfont: ['setting'],
    cap: ['wire'],
    class: ['net', 'clearance'],
    color: ['layer'],
    columns: ['frame'],
    constant: ['attribute'],
    coord: ['port'],
    cream: ['smd'],
    curve: ['wire', 'vertex'],
    device: ['part'],
    deviceset: ['part'],
    diameter: ['pad', 'via'],
    direction: ['pin', 'port'],
    display: ['grid', 'attribute'],
    distance: ['grid', 'text'],
    drill: ['pad', 'class', 'hole', 'via'],
    dtype: ['dimension'],
    dx: ['smd', 'module'],
    dy: ['smd', 'module'],
    element: ['contactref'],
    encoding: ['version'],
    extent: ['wire', 'via'],
    extwidth: ['dimension'],
    fill: ['layer'],
    first: ['pad'],
    font: ['text', 'attribute'],
    function: ['pin'],
    gate: ['connect', 'instance', 'pinref'],
    hash: ['approved'],
    isolate: ['polygon'],
    language: ['description'],
    layer: ['wire', 'text', 'rectangle', 'circle', 'smd', 'label', 'attribute', 'polygon', 'frame', 'dimension'],
    length: ['pin'],
    library: ['part', 'element'],
    minversion: ['note'],
    module: ['moduleinst'],
    moduleinst: ['portref'],
    multiple: ['grid'],
    name: [
      'layer',
      'library',
      'package',
      'pad',
      'symbol',
      'pin',
      'deviceset',
      'gate',
      'device',
      'technology',
      'class',
      'part',
      'net',
      'smd',
      'attribute',
      'module',
      'port',
      'moduleinst',
      'bus',
      'designrules',
      'param',
      'pass',
      'element',
      'signal',
    ],
    number: ['layer', 'class'],
    package: ['device', 'element'],
    pad: ['connect', 'contactref'],
    part: ['instance', 'pinref'],
    pin: ['connect', 'pinref'],
    port: ['portref'],
    precision: ['dimension'],
    prefix: ['deviceset', 'module'],
    radius: ['circle'],
    ratio: ['text', 'attribute', 'label'],
    refer: ['pass'],
    rot: ['pad', 'text', 'pin', 'rectangle', 'instance', 'attribute', 'smd', 'label', 'element'],
    roundness: ['smd'],
    route: ['connect'],
    rows: ['frame'],
    severity: ['note'],
    shape: ['pad', 'via'],
    side: ['port'],
    size: ['text', 'label', 'attribute'],
    smashed: ['instance', 'element'],
    stop: ['pad', 'smd'],
    style: ['grid', 'wire'],
    swaplevel: ['pin', 'gate'],
    symbol: ['gate'],
    technology: ['part'],
    textratio: ['dimension'],
    textsize: ['dimension'],
    thermals: ['pad', 'smd', 'polygon'],
    unit: ['grid', 'dimension'],
    unitdist: ['grid'],
    uservalue: ['deviceset'],
    value: ['part', 'clearance', 'attribute', 'param', 'element'],
    version: ['eagle', 'note'],
    verticaltext: ['setting'],
    visible: ['layer', 'pin', 'dimension'],
    width: ['wire', 'circle', 'class', 'polygon', 'dimension'],
    x: ['pad', 'text', 'pin', 'circle', 'gate', 'instance', 'junction', 'smd', 'label', 'attribute', 'vertex', 'hole', 'moduleinst', 'element', 'via'],
    x1: ['wire', 'rectangle', 'frame', 'dimension'],
    x2: ['wire', 'rectangle', 'frame', 'dimension'],
    x3: ['dimension'],
    xref: ['label'],
    xreflabel: ['schematic'],
    xrefpart: ['schematic'],
    y: ['pad', 'text', 'pin', 'circle', 'gate', 'instance', 'junction', 'smd', 'label', 'attribute', 'vertex', 'hole', 'moduleinst', 'element', 'via'],
    y1: ['wire', 'rectangle', 'frame', 'dimension'],
    y2: ['wire', 'rectangle', 'frame', 'dimension'],
    y3: ['dimension'],
  },
};
