#include "./jsbindings.h"
#include "./geometry.h"
#include "../quickjs/cutils.h"

#include <opencv2/imgcodecs.hpp>

#if defined(JS_CV_MODULE) || defined(quickjs_cv_EXPORTS)
#define JS_INIT_MODULE /*VISIBLE*/ js_init_module
#else
#define JS_INIT_MODULE VISIBLE js_init_module_cv
#endif

static JSValue
js_cv_ctor(JSContext* ctx, JSValueConst new_target, int argc, JSValueConst* argv) {
  JSValue obj = JS_UNDEFINED;
  JSValue proto;
  JSSizeData size;

  return obj;
}

static JSValue
js_cv_hough_lines(JSContext* ctx, JSValueConst this_val, int argc, JSValueConst* argv) {
  cv::Mat* image;
  JSValue array;
  double rho, theta;
  int32_t threshold;
  double srn = 0, stn = 0, min_theta = 0, max_theta = CV_PI;
  std::vector<cv::Vec4i> lines;

  double angle = 0, scale = 1;
  cv::Mat m;

  JSValue ret;
  if(argc < 5)
    return JS_EXCEPTION;

  image = js_mat_data(ctx, argv[0]);

  if(image == nullptr)
    return JS_EXCEPTION;

  array = argv[1];
  JS_ToFloat64(ctx, &rho, argv[2]);
  JS_ToFloat64(ctx, &theta, argv[3]);
  JS_ToInt32(ctx, &threshold, argv[4]);

  if(argc >= 6)
    JS_ToFloat64(ctx, &srn, argv[5]);
  if(argc >= 7)
    JS_ToFloat64(ctx, &stn, argv[6]);

  if(argc >= 8)
    JS_ToFloat64(ctx, &min_theta, argv[7]);
  if(argc >= 9)
    JS_ToFloat64(ctx, &max_theta, argv[8]);

  cv::HoughLines(*image, lines, rho, theta, threshold, srn, stn, min_theta, max_theta);

  return JS_UNDEFINED;
}

static JSValue
js_cv_imread(JSContext* ctx, JSValueConst this_val, int argc, JSValueConst* argv) {

  const char* filename = JS_ToCString(ctx, argv[0]);

  cv::Mat mat = cv::imread(filename);

  return js_mat_wrap(ctx, mat);
}

static JSValue
js_cv_cvt_color(JSContext* ctx, JSValueConst this_val, int argc, JSValueConst* argv) {

  cv::Mat *src, *dst;
  int code, dstCn = 0;

  src = js_mat_data(ctx,argv[0]);
  dst = js_mat_data(ctx,argv[1]);

  if(src == nullptr || dst == nullptr)
    return JS_EXCEPTION;

  JS_ToInt32(ctx, &code, argv[2]);

  if(argc >= 4)
    JS_ToInt32(ctx, &dstCn, argv[3]);

  cv::cvtColor(*src, *dst, code, dstCn);
  return JS_UNDEFINED;
}

JSValue cv_proto, cv_class;
JSClassID js_cv_class_id;

JSClassDef js_cv_class = {"cv"};

const JSCFunctionListEntry js_cv_static_funcs[] = {
    JS_CFUNC_DEF("HoughLines", 5, js_cv_hough_lines),
    JS_CFUNC_DEF("imread", 1, js_cv_imread),
    JS_CFUNC_DEF("cvtColor", 3, js_cv_cvt_color),
    JS_PROP_INT32_DEF("CV_VERSION_MAJOR", CV_VERSION_MAJOR, JS_PROP_ENUMERABLE),
    JS_PROP_INT32_DEF("CV_VERSION_MINOR", CV_VERSION_MINOR, JS_PROP_ENUMERABLE),
    JS_PROP_INT32_DEF("CV_VERSION_REVISION", CV_VERSION_REVISION, JS_PROP_ENUMERABLE),
    JS_PROP_STRING_DEF("CV_VERSION_STATUS", CV_VERSION_STATUS, JS_PROP_ENUMERABLE),
    JS_PROP_INT32_DEF("CV_CMP_EQ", CV_CMP_EQ, JS_PROP_ENUMERABLE),
    JS_PROP_INT32_DEF("CV_CMP_GT", CV_CMP_GT, JS_PROP_ENUMERABLE),
    JS_PROP_INT32_DEF("CV_CMP_GE", CV_CMP_GE, JS_PROP_ENUMERABLE),
    JS_PROP_INT32_DEF("CV_CMP_LT", CV_CMP_LT, JS_PROP_ENUMERABLE),
    JS_PROP_INT32_DEF("CV_CMP_LE", CV_CMP_LE, JS_PROP_ENUMERABLE),
    JS_PROP_INT32_DEF("CV_CMP_NE", CV_CMP_NE, JS_PROP_ENUMERABLE),
    JS_PROP_DOUBLE_DEF("CV_PI", CV_PI, JS_PROP_ENUMERABLE),
    JS_PROP_DOUBLE_DEF("CV_2PI", CV_2PI, JS_PROP_ENUMERABLE),
    JS_PROP_DOUBLE_DEF("CV_LOG2", CV_LOG2, JS_PROP_ENUMERABLE),
    JS_PROP_INT32_DEF("COLOR_BGR2BGRA", cv::COLOR_BGR2BGRA, 0),
    JS_PROP_INT32_DEF("COLOR_RGB2RGBA", cv::COLOR_RGB2RGBA, 0),
    JS_PROP_INT32_DEF("COLOR_BGRA2BGR", cv::COLOR_BGRA2BGR, 0),
    JS_PROP_INT32_DEF("COLOR_RGBA2RGB", cv::COLOR_RGBA2RGB, 0),
    JS_PROP_INT32_DEF("COLOR_BGR2RGBA", cv::COLOR_BGR2RGBA, 0),
    JS_PROP_INT32_DEF("COLOR_RGB2BGRA", cv::COLOR_RGB2BGRA, 0),
    JS_PROP_INT32_DEF("COLOR_RGBA2BGR", cv::COLOR_RGBA2BGR, 0),
    JS_PROP_INT32_DEF("COLOR_BGRA2RGB", cv::COLOR_BGRA2RGB, 0),
    JS_PROP_INT32_DEF("COLOR_BGR2RGB", cv::COLOR_BGR2RGB, 0),
    JS_PROP_INT32_DEF("COLOR_RGB2BGR", cv::COLOR_RGB2BGR, 0),
    JS_PROP_INT32_DEF("COLOR_BGRA2RGBA", cv::COLOR_BGRA2RGBA, 0),
    JS_PROP_INT32_DEF("COLOR_RGBA2BGRA", cv::COLOR_RGBA2BGRA, 0),
    JS_PROP_INT32_DEF("COLOR_BGR2GRAY", cv::COLOR_BGR2GRAY, 0),
    JS_PROP_INT32_DEF("COLOR_RGB2GRAY", cv::COLOR_RGB2GRAY, 0),
    JS_PROP_INT32_DEF("COLOR_GRAY2BGR", cv::COLOR_GRAY2BGR, 0),
    JS_PROP_INT32_DEF("COLOR_GRAY2RGB", cv::COLOR_GRAY2RGB, 0),
    JS_PROP_INT32_DEF("COLOR_GRAY2BGRA", cv::COLOR_GRAY2BGRA, 0),
    JS_PROP_INT32_DEF("COLOR_GRAY2RGBA", cv::COLOR_GRAY2RGBA, 0),
    JS_PROP_INT32_DEF("COLOR_BGRA2GRAY", cv::COLOR_BGRA2GRAY, 0),
    JS_PROP_INT32_DEF("COLOR_RGBA2GRAY", cv::COLOR_RGBA2GRAY, 0),
    JS_PROP_INT32_DEF("COLOR_BGR2BGR565", cv::COLOR_BGR2BGR565, 0),
    JS_PROP_INT32_DEF("COLOR_RGB2BGR565", cv::COLOR_RGB2BGR565, 0),
    JS_PROP_INT32_DEF("COLOR_BGR5652BGR", cv::COLOR_BGR5652BGR, 0),
    JS_PROP_INT32_DEF("COLOR_BGR5652RGB", cv::COLOR_BGR5652RGB, 0),
    JS_PROP_INT32_DEF("COLOR_BGRA2BGR565", cv::COLOR_BGRA2BGR565, 0),
    JS_PROP_INT32_DEF("COLOR_RGBA2BGR565", cv::COLOR_RGBA2BGR565, 0),
    JS_PROP_INT32_DEF("COLOR_BGR5652BGRA", cv::COLOR_BGR5652BGRA, 0),
    JS_PROP_INT32_DEF("COLOR_BGR5652RGBA", cv::COLOR_BGR5652RGBA, 0),
    JS_PROP_INT32_DEF("COLOR_GRAY2BGR565", cv::COLOR_GRAY2BGR565, 0),
    JS_PROP_INT32_DEF("COLOR_BGR5652GRAY", cv::COLOR_BGR5652GRAY, 0),
    JS_PROP_INT32_DEF("COLOR_BGR2BGR555", cv::COLOR_BGR2BGR555, 0),
    JS_PROP_INT32_DEF("COLOR_RGB2BGR555", cv::COLOR_RGB2BGR555, 0),
    JS_PROP_INT32_DEF("COLOR_BGR5552BGR", cv::COLOR_BGR5552BGR, 0),
    JS_PROP_INT32_DEF("COLOR_BGR5552RGB", cv::COLOR_BGR5552RGB, 0),
    JS_PROP_INT32_DEF("COLOR_BGRA2BGR555", cv::COLOR_BGRA2BGR555, 0),
    JS_PROP_INT32_DEF("COLOR_RGBA2BGR555", cv::COLOR_RGBA2BGR555, 0),
    JS_PROP_INT32_DEF("COLOR_BGR5552BGRA", cv::COLOR_BGR5552BGRA, 0),
    JS_PROP_INT32_DEF("COLOR_BGR5552RGBA", cv::COLOR_BGR5552RGBA, 0),
    JS_PROP_INT32_DEF("COLOR_GRAY2BGR555", cv::COLOR_GRAY2BGR555, 0),
    JS_PROP_INT32_DEF("COLOR_BGR5552GRAY", cv::COLOR_BGR5552GRAY, 0),
    JS_PROP_INT32_DEF("COLOR_BGR2XYZ", cv::COLOR_BGR2XYZ, 0),
    JS_PROP_INT32_DEF("COLOR_RGB2XYZ", cv::COLOR_RGB2XYZ, 0),
    JS_PROP_INT32_DEF("COLOR_XYZ2BGR", cv::COLOR_XYZ2BGR, 0),
    JS_PROP_INT32_DEF("COLOR_XYZ2RGB", cv::COLOR_XYZ2RGB, 0),
    JS_PROP_INT32_DEF("COLOR_BGR2YCrCb", cv::COLOR_BGR2YCrCb, 0),
    JS_PROP_INT32_DEF("COLOR_RGB2YCrCb", cv::COLOR_RGB2YCrCb, 0),
    JS_PROP_INT32_DEF("COLOR_YCrCb2BGR", cv::COLOR_YCrCb2BGR, 0),
    JS_PROP_INT32_DEF("COLOR_YCrCb2RGB", cv::COLOR_YCrCb2RGB, 0),
    JS_PROP_INT32_DEF("COLOR_BGR2HSV", cv::COLOR_BGR2HSV, 0),
    JS_PROP_INT32_DEF("COLOR_RGB2HSV", cv::COLOR_RGB2HSV, 0),
    JS_PROP_INT32_DEF("COLOR_BGR2Lab", cv::COLOR_BGR2Lab, 0),
    JS_PROP_INT32_DEF("COLOR_RGB2Lab", cv::COLOR_RGB2Lab, 0),
    JS_PROP_INT32_DEF("COLOR_BGR2Luv", cv::COLOR_BGR2Luv, 0),
    JS_PROP_INT32_DEF("COLOR_RGB2Luv", cv::COLOR_RGB2Luv, 0),
    JS_PROP_INT32_DEF("COLOR_BGR2HLS", cv::COLOR_BGR2HLS, 0),
    JS_PROP_INT32_DEF("COLOR_RGB2HLS", cv::COLOR_RGB2HLS, 0),
    JS_PROP_INT32_DEF("COLOR_HSV2BGR", cv::COLOR_HSV2BGR, 0),
    JS_PROP_INT32_DEF("COLOR_HSV2RGB", cv::COLOR_HSV2RGB, 0),
    JS_PROP_INT32_DEF("COLOR_Lab2BGR", cv::COLOR_Lab2BGR, 0),
    JS_PROP_INT32_DEF("COLOR_Lab2RGB", cv::COLOR_Lab2RGB, 0),
    JS_PROP_INT32_DEF("COLOR_Luv2BGR", cv::COLOR_Luv2BGR, 0),
    JS_PROP_INT32_DEF("COLOR_Luv2RGB", cv::COLOR_Luv2RGB, 0),
    JS_PROP_INT32_DEF("COLOR_HLS2BGR", cv::COLOR_HLS2BGR, 0),
    JS_PROP_INT32_DEF("COLOR_HLS2RGB", cv::COLOR_HLS2RGB, 0),
    JS_PROP_INT32_DEF("COLOR_BGR2HSV_FULL", cv::COLOR_BGR2HSV_FULL, 0),
    JS_PROP_INT32_DEF("COLOR_RGB2HSV_FULL", cv::COLOR_RGB2HSV_FULL, 0),
    JS_PROP_INT32_DEF("COLOR_BGR2HLS_FULL", cv::COLOR_BGR2HLS_FULL, 0),
    JS_PROP_INT32_DEF("COLOR_RGB2HLS_FULL", cv::COLOR_RGB2HLS_FULL, 0),
    JS_PROP_INT32_DEF("COLOR_HSV2BGR_FULL", cv::COLOR_HSV2BGR_FULL, 0),
    JS_PROP_INT32_DEF("COLOR_HSV2RGB_FULL", cv::COLOR_HSV2RGB_FULL, 0),
    JS_PROP_INT32_DEF("COLOR_HLS2BGR_FULL", cv::COLOR_HLS2BGR_FULL, 0),
    JS_PROP_INT32_DEF("COLOR_HLS2RGB_FULL", cv::COLOR_HLS2RGB_FULL, 0),
    JS_PROP_INT32_DEF("COLOR_LBGR2Lab", cv::COLOR_LBGR2Lab, 0),
    JS_PROP_INT32_DEF("COLOR_LRGB2Lab", cv::COLOR_LRGB2Lab, 0),
    JS_PROP_INT32_DEF("COLOR_LBGR2Luv", cv::COLOR_LBGR2Luv, 0),
    JS_PROP_INT32_DEF("COLOR_LRGB2Luv", cv::COLOR_LRGB2Luv, 0),
    JS_PROP_INT32_DEF("COLOR_Lab2LBGR", cv::COLOR_Lab2LBGR, 0),
    JS_PROP_INT32_DEF("COLOR_Lab2LRGB", cv::COLOR_Lab2LRGB, 0),
    JS_PROP_INT32_DEF("COLOR_Luv2LBGR", cv::COLOR_Luv2LBGR, 0),
    JS_PROP_INT32_DEF("COLOR_Luv2LRGB", cv::COLOR_Luv2LRGB, 0),
    JS_PROP_INT32_DEF("COLOR_BGR2YUV", cv::COLOR_BGR2YUV, 0),
    JS_PROP_INT32_DEF("COLOR_RGB2YUV", cv::COLOR_RGB2YUV, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGR", cv::COLOR_YUV2BGR, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGB", cv::COLOR_YUV2RGB, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGB_NV12", cv::COLOR_YUV2RGB_NV12, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGR_NV12", cv::COLOR_YUV2BGR_NV12, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGB_NV21", cv::COLOR_YUV2RGB_NV21, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGR_NV21", cv::COLOR_YUV2BGR_NV21, 0),
    JS_PROP_INT32_DEF("COLOR_YUV420sp2RGB", cv::COLOR_YUV420sp2RGB, 0),
    JS_PROP_INT32_DEF("COLOR_YUV420sp2BGR", cv::COLOR_YUV420sp2BGR, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGBA_NV12", cv::COLOR_YUV2RGBA_NV12, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGRA_NV12", cv::COLOR_YUV2BGRA_NV12, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGBA_NV21", cv::COLOR_YUV2RGBA_NV21, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGRA_NV21", cv::COLOR_YUV2BGRA_NV21, 0),
    JS_PROP_INT32_DEF("COLOR_YUV420sp2RGBA", cv::COLOR_YUV420sp2RGBA, 0),
    JS_PROP_INT32_DEF("COLOR_YUV420sp2BGRA", cv::COLOR_YUV420sp2BGRA, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGB_YV12", cv::COLOR_YUV2RGB_YV12, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGR_YV12", cv::COLOR_YUV2BGR_YV12, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGB_IYUV", cv::COLOR_YUV2RGB_IYUV, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGR_IYUV", cv::COLOR_YUV2BGR_IYUV, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGB_I420", cv::COLOR_YUV2RGB_I420, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGR_I420", cv::COLOR_YUV2BGR_I420, 0),
    JS_PROP_INT32_DEF("COLOR_YUV420p2RGB", cv::COLOR_YUV420p2RGB, 0),
    JS_PROP_INT32_DEF("COLOR_YUV420p2BGR", cv::COLOR_YUV420p2BGR, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGBA_YV12", cv::COLOR_YUV2RGBA_YV12, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGRA_YV12", cv::COLOR_YUV2BGRA_YV12, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGBA_IYUV", cv::COLOR_YUV2RGBA_IYUV, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGRA_IYUV", cv::COLOR_YUV2BGRA_IYUV, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGBA_I420", cv::COLOR_YUV2RGBA_I420, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGRA_I420", cv::COLOR_YUV2BGRA_I420, 0),
    JS_PROP_INT32_DEF("COLOR_YUV420p2RGBA", cv::COLOR_YUV420p2RGBA, 0),
    JS_PROP_INT32_DEF("COLOR_YUV420p2BGRA", cv::COLOR_YUV420p2BGRA, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2GRAY_420", cv::COLOR_YUV2GRAY_420, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2GRAY_NV21", cv::COLOR_YUV2GRAY_NV21, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2GRAY_NV12", cv::COLOR_YUV2GRAY_NV12, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2GRAY_YV12", cv::COLOR_YUV2GRAY_YV12, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2GRAY_IYUV", cv::COLOR_YUV2GRAY_IYUV, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2GRAY_I420", cv::COLOR_YUV2GRAY_I420, 0),
    JS_PROP_INT32_DEF("COLOR_YUV420sp2GRAY", cv::COLOR_YUV420sp2GRAY, 0),
    JS_PROP_INT32_DEF("COLOR_YUV420p2GRAY", cv::COLOR_YUV420p2GRAY, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGB_UYVY", cv::COLOR_YUV2RGB_UYVY, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGR_UYVY", cv::COLOR_YUV2BGR_UYVY, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGB_Y422", cv::COLOR_YUV2RGB_Y422, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGR_Y422", cv::COLOR_YUV2BGR_Y422, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGB_UYNV", cv::COLOR_YUV2RGB_UYNV, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGR_UYNV", cv::COLOR_YUV2BGR_UYNV, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGBA_UYVY", cv::COLOR_YUV2RGBA_UYVY, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGRA_UYVY", cv::COLOR_YUV2BGRA_UYVY, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGBA_Y422", cv::COLOR_YUV2RGBA_Y422, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGRA_Y422", cv::COLOR_YUV2BGRA_Y422, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGBA_UYNV", cv::COLOR_YUV2RGBA_UYNV, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGRA_UYNV", cv::COLOR_YUV2BGRA_UYNV, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGB_YUY2", cv::COLOR_YUV2RGB_YUY2, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGR_YUY2", cv::COLOR_YUV2BGR_YUY2, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGB_YVYU", cv::COLOR_YUV2RGB_YVYU, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGR_YVYU", cv::COLOR_YUV2BGR_YVYU, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGB_YUYV", cv::COLOR_YUV2RGB_YUYV, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGR_YUYV", cv::COLOR_YUV2BGR_YUYV, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGB_YUNV", cv::COLOR_YUV2RGB_YUNV, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGR_YUNV", cv::COLOR_YUV2BGR_YUNV, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGBA_YUY2", cv::COLOR_YUV2RGBA_YUY2, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGRA_YUY2", cv::COLOR_YUV2BGRA_YUY2, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGBA_YVYU", cv::COLOR_YUV2RGBA_YVYU, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGRA_YVYU", cv::COLOR_YUV2BGRA_YVYU, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGBA_YUYV", cv::COLOR_YUV2RGBA_YUYV, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGRA_YUYV", cv::COLOR_YUV2BGRA_YUYV, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2RGBA_YUNV", cv::COLOR_YUV2RGBA_YUNV, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2BGRA_YUNV", cv::COLOR_YUV2BGRA_YUNV, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2GRAY_UYVY", cv::COLOR_YUV2GRAY_UYVY, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2GRAY_YUY2", cv::COLOR_YUV2GRAY_YUY2, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2GRAY_Y422", cv::COLOR_YUV2GRAY_Y422, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2GRAY_UYNV", cv::COLOR_YUV2GRAY_UYNV, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2GRAY_YVYU", cv::COLOR_YUV2GRAY_YVYU, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2GRAY_YUYV", cv::COLOR_YUV2GRAY_YUYV, 0),
    JS_PROP_INT32_DEF("COLOR_YUV2GRAY_YUNV", cv::COLOR_YUV2GRAY_YUNV, 0),
    JS_PROP_INT32_DEF("COLOR_RGBA2mRGBA", cv::COLOR_RGBA2mRGBA, 0),
    JS_PROP_INT32_DEF("COLOR_mRGBA2RGBA", cv::COLOR_mRGBA2RGBA, 0),
    JS_PROP_INT32_DEF("COLOR_RGB2YUV_I420", cv::COLOR_RGB2YUV_I420, 0),
    JS_PROP_INT32_DEF("COLOR_BGR2YUV_I420", cv::COLOR_BGR2YUV_I420, 0),
    JS_PROP_INT32_DEF("COLOR_RGB2YUV_IYUV", cv::COLOR_RGB2YUV_IYUV, 0),
    JS_PROP_INT32_DEF("COLOR_BGR2YUV_IYUV", cv::COLOR_BGR2YUV_IYUV, 0),
    JS_PROP_INT32_DEF("COLOR_RGBA2YUV_I420", cv::COLOR_RGBA2YUV_I420, 0),
    JS_PROP_INT32_DEF("COLOR_BGRA2YUV_I420", cv::COLOR_BGRA2YUV_I420, 0),
    JS_PROP_INT32_DEF("COLOR_RGBA2YUV_IYUV", cv::COLOR_RGBA2YUV_IYUV, 0),
    JS_PROP_INT32_DEF("COLOR_BGRA2YUV_IYUV", cv::COLOR_BGRA2YUV_IYUV, 0),
    JS_PROP_INT32_DEF("COLOR_RGB2YUV_YV12", cv::COLOR_RGB2YUV_YV12, 0),
    JS_PROP_INT32_DEF("COLOR_BGR2YUV_YV12", cv::COLOR_BGR2YUV_YV12, 0),
    JS_PROP_INT32_DEF("COLOR_RGBA2YUV_YV12", cv::COLOR_RGBA2YUV_YV12, 0),
    JS_PROP_INT32_DEF("COLOR_BGRA2YUV_YV12", cv::COLOR_BGRA2YUV_YV12, 0),
    JS_PROP_INT32_DEF("COLOR_BayerBG2BGR", cv::COLOR_BayerBG2BGR, 0),
    JS_PROP_INT32_DEF("COLOR_BayerGB2BGR", cv::COLOR_BayerGB2BGR, 0),
    JS_PROP_INT32_DEF("COLOR_BayerRG2BGR", cv::COLOR_BayerRG2BGR, 0),
    JS_PROP_INT32_DEF("COLOR_BayerGR2BGR", cv::COLOR_BayerGR2BGR, 0),
    JS_PROP_INT32_DEF("COLOR_BayerBG2RGB", cv::COLOR_BayerBG2RGB, 0),
    JS_PROP_INT32_DEF("COLOR_BayerGB2RGB", cv::COLOR_BayerGB2RGB, 0),
    JS_PROP_INT32_DEF("COLOR_BayerRG2RGB", cv::COLOR_BayerRG2RGB, 0),
    JS_PROP_INT32_DEF("COLOR_BayerGR2RGB", cv::COLOR_BayerGR2RGB, 0),
    JS_PROP_INT32_DEF("COLOR_BayerBG2GRAY", cv::COLOR_BayerBG2GRAY, 0),
    JS_PROP_INT32_DEF("COLOR_BayerGB2GRAY", cv::COLOR_BayerGB2GRAY, 0),
    JS_PROP_INT32_DEF("COLOR_BayerRG2GRAY", cv::COLOR_BayerRG2GRAY, 0),
    JS_PROP_INT32_DEF("COLOR_BayerGR2GRAY", cv::COLOR_BayerGR2GRAY, 0),
    JS_PROP_INT32_DEF("COLOR_BayerBG2BGR_VNG", cv::COLOR_BayerBG2BGR_VNG, 0),
    JS_PROP_INT32_DEF("COLOR_BayerGB2BGR_VNG", cv::COLOR_BayerGB2BGR_VNG, 0),
    JS_PROP_INT32_DEF("COLOR_BayerRG2BGR_VNG", cv::COLOR_BayerRG2BGR_VNG, 0),
    JS_PROP_INT32_DEF("COLOR_BayerGR2BGR_VNG", cv::COLOR_BayerGR2BGR_VNG, 0),
    JS_PROP_INT32_DEF("COLOR_BayerBG2RGB_VNG", cv::COLOR_BayerBG2RGB_VNG, 0),
    JS_PROP_INT32_DEF("COLOR_BayerGB2RGB_VNG", cv::COLOR_BayerGB2RGB_VNG, 0),
    JS_PROP_INT32_DEF("COLOR_BayerRG2RGB_VNG", cv::COLOR_BayerRG2RGB_VNG, 0),
    JS_PROP_INT32_DEF("COLOR_BayerGR2RGB_VNG", cv::COLOR_BayerGR2RGB_VNG, 0),
    JS_PROP_INT32_DEF("COLOR_BayerBG2BGR_EA", cv::COLOR_BayerBG2BGR_EA, 0),
    JS_PROP_INT32_DEF("COLOR_BayerGB2BGR_EA", cv::COLOR_BayerGB2BGR_EA, 0),
    JS_PROP_INT32_DEF("COLOR_BayerRG2BGR_EA", cv::COLOR_BayerRG2BGR_EA, 0),
    JS_PROP_INT32_DEF("COLOR_BayerGR2BGR_EA", cv::COLOR_BayerGR2BGR_EA, 0),
    JS_PROP_INT32_DEF("COLOR_BayerBG2RGB_EA", cv::COLOR_BayerBG2RGB_EA, 0),
    JS_PROP_INT32_DEF("COLOR_BayerGB2RGB_EA", cv::COLOR_BayerGB2RGB_EA, 0),
    JS_PROP_INT32_DEF("COLOR_BayerRG2RGB_EA", cv::COLOR_BayerRG2RGB_EA, 0),
    JS_PROP_INT32_DEF("COLOR_BayerGR2RGB_EA", cv::COLOR_BayerGR2RGB_EA, 0),
    JS_PROP_INT32_DEF("COLOR_BayerBG2BGRA", cv::COLOR_BayerBG2BGRA, 0),
    JS_PROP_INT32_DEF("COLOR_BayerGB2BGRA", cv::COLOR_BayerGB2BGRA, 0),
    JS_PROP_INT32_DEF("COLOR_BayerRG2BGRA", cv::COLOR_BayerRG2BGRA, 0),
    JS_PROP_INT32_DEF("COLOR_BayerGR2BGRA", cv::COLOR_BayerGR2BGRA, 0),
    JS_PROP_INT32_DEF("COLOR_BayerBG2RGBA", cv::COLOR_BayerBG2RGBA, 0),
    JS_PROP_INT32_DEF("COLOR_BayerGB2RGBA", cv::COLOR_BayerGB2RGBA, 0),
    JS_PROP_INT32_DEF("COLOR_BayerRG2RGBA", cv::COLOR_BayerRG2RGBA, 0),
    JS_PROP_INT32_DEF("COLOR_BayerGR2RGBA", cv::COLOR_BayerGR2RGBA, 0),

};

int
js_cv_init(JSContext* ctx, JSModuleDef* m) {
  cv_class = JS_NewObject(ctx);
  JS_SetPropertyFunctionList(ctx, cv_class, js_cv_static_funcs, countof(js_cv_static_funcs));
  JSValue g = JS_GetGlobalObject(ctx);

  int32array_ctor = JS_GetProperty(ctx, g, JS_ATOM_Int32Array);
  int32array_proto = JS_GetPrototype(ctx, int32array_ctor);

  if(m)
    JS_SetModuleExport(ctx, m, "cv", cv_class);

  return 0;
}

extern "C" JSModuleDef*
JS_INIT_MODULE(JSContext* ctx, const char* module_name) {
  JSModuleDef* m;
  m = JS_NewCModule(ctx, module_name, &js_cv_init);
  if(!m)
    return NULL;
  JS_AddModuleExport(ctx, m, "cv");
  return m;
}
